InfoBankApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from .views import index
from infobank.views import secureFile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('appauth.urls')),
    path("", index, name="index"),
    path("login", index, name="index"),
    re_path(r'^app/.*$', index, name='index'),
    path('api/', include('infobank.urls')),
    re_path(r'^media/.*$', secureFile.as_view(), name="secureFile"),
    # path('', include('infobank.urls')),
] 

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

appauth/urls.py
from django.urls import path
from knox import views as knox_views
from django.conf.urls import url, include
from .views import *

app_name = 'auth'

urlpatterns = [
    # Auth API
    path('login/', LoginAPI.as_view(), name="login"),
    path('password/', PasswordAPI.as_view()),
    path('change-password/', ChangePasswordAPI.as_view()),
    path('user/', UserAPI.as_view()),
    path('manage-user/', ManageUserAPI.as_view()),
    path('manage-user/<int:id>', ManageUserAPI.as_view()),
    path('logout/', knox_views.LogoutView.as_view(), name='knox_logout'),
    path('search/', SearchAPI.as_view()),
    # groups
    path('groups/', GroupsAPI.as_view()),
    # Designations
    path('designations/', DesignationAPI.as_view()),
    
    ## user creation 
    path('upload/users/', CreateUserAllAPI.as_view()),
]

infobank/urls.py
from django.urls import path
from .views import *

app_name = 'infobank'

urlpatterns = [
    # path('', home, name="home"), 
    #  path('category/<slug:slug>/',category_details, name="category_details"),
    # path('folder/<int:id>/', folder_details, name="folder_details"),

    path('category/<slug:slug>/', CategoryDetails.as_view(),
         name="category_details"),
    path('folder/<int:id>/', FolderDetails.as_view(), name="folder_details"),
    path('manage-folder/', ManageFolderView.as_view(), name="manage_folder"),
    path('manage-file/', ManageFileView.as_view(), name="manage_file"),


    path('share-content/', ShareContent.as_view(), name="share_content"),
    

    # path('users/', ManageUser.as_view(), name="manage_users"),
    # path('user/<int:id>', ManageUser.as_view(), name="manage_single_users"),

]

infobank/models.py
import os
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.text import slugify
from appauth.models import User
from django.contrib.auth.models import Group


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=250, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    owners = models.ManyToManyField(User, blank=True) 

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Folder(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, null=True, blank=True)
    description = models.CharField(
        max_length=250, null=True, blank=True, default="")
    category = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.CASCADE)
    parent_directory = models.ForeignKey(
        'self', null=True, blank=True, on_delete=models.CASCADE)
    created_by = models.ForeignKey(
        User, null=True, on_delete=models.SET_NULL, related_name='folder_creator')
    created_date = models.DateTimeField(auto_now_add=True)
    owners = models.ManyToManyField(
        User, blank=True)
    
    def __str__(self):
        if not self.parent_directory:
            return "{0} > {1}".format(self.category.name, self.name)
        else:
            pwd = self
            dir_list = []
            dir_list.insert(0, self.category.name)
            dir_list.insert(1, pwd.name)
            while pwd.parent_directory != None:
                dir_list.insert(1, pwd.parent_directory.name)
                pwd = pwd.parent_directory

            return " > ".join(dir_list)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Folder, self).save(*args, **kwargs)
    class Meta:
        permissions = (
            ('custom_folder', 'Custom folder'),
        )

def department_directory_path(instance, filename):
    if instance.folder:
        return '{0}/{1}/{2}'.format(instance.category.name, instance.folder.name, filename)
    else:
        return '{0}/{1}'.format(instance.category.name, filename)


class File(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(
        max_length=250, null=True, blank=True, default="")
    file = models.FileField(upload_to=department_directory_path)
    folder = models.ForeignKey(
        Folder, null=True, blank=True, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension
    class Meta:
        permissions = (
            ('custom_file', 'Custom file'),
        )

infobank/views.py
from django.shortcuts import render, redirect
from rest_framework import viewsets, permissions, generics, mixins
from django.core import serializers
from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework import permissions
from django.core.exceptions import PermissionDenied
from django.utils import timezone
from rest_framework.views import APIView
from django.shortcuts import get_object_or_404
# Pagination for REST FRAMEWORK TAKEN
from rest_framework.pagination import LimitOffsetPagination
from django_filters.rest_framework import DjangoFilterBackend, FilterSet
from rest_framework.filters import OrderingFilter, SearchFilter
from rest_framework.parsers import MultiPartParser
from django.http import HttpResponse

# FOR PUT & DELETE METHODS
from django.http import QueryDict

# Auth
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, JsonResponse, FileResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db import IntegrityError

# from .serializers import DepartmentSerializer
from appauth.models import User
from .models import Category, Folder, File
from .serializers import *
from django.views import View
from appauth.serializers import UserShortSerializer
from guardian.shortcuts import assign_perm,get_users_with_perms,remove_perm
from guardian.shortcuts import get_objects_for_user
# Create your views here.

def find_breadcumbs(folder):
    pwd = folder
    breadcumbs = []
    breadcumbs.insert(0, folder)
    while pwd.parent_directory != None:
        breadcumbs.insert(0, pwd.parent_directory)
        pwd = pwd.parent_directory
    return breadcumbs

class CategoryDetails(APIView):
    permission_classes = [
        permissions.IsAuthenticated
    ]

    def get(self, request, slug):
        if slug == "shared":
            category = Category.objects.get(slug="personal")
           
            try:
                category_serializer = CategoryDetailsSerialiser(category, context={"user":request.user,"type":"shared"})
            except:
                return Response(category_serializer.error, status=status.HTTP_400_BAD_REQUEST)
        elif slug == "personal":    
            category = Category.objects.get(slug=slug)
           
            try:
                category_serializer = CategoryDetailsSerialiser(category, context={"user":request.user,"type":"personal"})
            except:
                return Response(category_serializer.error, status=status.HTTP_400_BAD_REQUEST)
        perm_change = request.user.has_perm('change_category', category)
        # perm_view = request.user.has_perm('view_category', category)

        # if perm_view:
        can_upload = False
        can_add_folder = False
        if request.user.is_staff:
            can_upload = True
            can_add_folder = True
        elif request.user in category.owners.all():
            can_upload = True

        context = {
            "category": category_serializer.data,
            'folder': None,
            'can_upload': can_upload,
            'can_add_folder': can_add_folder,

        }
        return Response(context, status=status.HTTP_200_OK)
        
class secureFile(APIView):
    permission_classes = [
        permissions.IsAuthenticated
    ]
    def get(self, request):
        path, filename =  request.path_info.split("media/")
        document =get_object_or_404(File, file=filename) 
        perm_view = request.user.has_perm('view_file', document)
        media_path="media/"+filename
        if perm_view:
            with open(media_path, "rb") as f:
                file_data = f.read()

            # sending response 
            response = HttpResponse(file_data, content_type='application/file')
            response['Content-Disposition'] = 'inline; filename='+os.path.basename(media_path)
            return response
        else:
            return Response(status=status.HTTP_401_UNAUTHORIZED)
    
class FolderDetails(APIView):
    permission_classes = [
        permissions.IsAuthenticated
    ]

    def get(self, request, id):
        folder = Folder.objects.get(id=id)
        perm_change = request.user.has_perm('change_folder', folder)
        perm_view = request.user.has_perm('view_folder', folder)
       
        if perm_view:
            try:
                folder_serializer = FolderDetailSerialiser(folder, context={"user":request.user} )
            except:
                return Response(folder_serializer.error, status=status.HTTP_400_BAD_REQUEST)
            # BREADCUMBS
            breadcumbs = find_breadcumbs(folder)
            breadcumbs_serializer = FolderSerialiser(breadcumbs, context={"user":request.user}, many=True)
            can_upload = False
            can_add_folder = False
            
            if request.user.is_staff or perm_change:
                can_upload = True
                can_add_folder = True
            elif request.user in folder.category.owners.all():
                can_upload = True
            elif request.user in folder.owners.all():
                can_upload = True
           
            context = {
                "folder": folder_serializer.data,
                'breadcumbs': breadcumbs_serializer.data,
                'can_upload': can_upload,
                'can_add_folder': can_add_folder,
            
            }
            return Response(context, status=status.HTTP_200_OK)
        else:
            return Response(status=status.HTTP_401_UNAUTHORIZED)

class ShareContent(APIView):
    permission_classes = [
        permissions.IsAuthenticated
    ]
    def get(self, request):
        id = request.GET.get("id")
        type = request.GET.get("type")
        if type == "folder":
            folder = Folder.objects.get(id= id)
            userList = get_users_with_perms(folder, attach_perms=True)
            users=[]
            for user, permissions in userList.items():
                user_details = UserShortSerializer(user).data
                if "change_folder" in permissions:
                    user_permission= "edit"
                    users.append({
                        'user':user_details,
                        'permissions':user_permission,
                        "owner":(folder.created_by == user)
                    })
                elif "view_folder" in permissions: 
                    user_permission= "view"
                    users.append({
                        'user':user_details,
                        'permissions':user_permission,
                        "owner":(folder.created_by == user)
                    })
        elif type == "file":
            file = File.objects.get(id= id)
            userList = get_users_with_perms(file, attach_perms=True)
            users=[]
            for user, permissions in userList.items():
                user_details = UserShortSerializer(user).data
                if "change_file" in permissions:
                    user_permission= "edit"
                    users.append({
                        'user':user_details,
                        'permissions':user_permission,
                        "owner":(file.created_by == user)
                    })
                elif "view_file" in permissions: 
                    user_permission= "view"
                    users.append({
                        'user':user_details,
                        'permissions':user_permission,
                         "owner":(file.created_by == user)
                    })  

        return Response(list(users), status=status.HTTP_200_OK)

    def put(self, request):
        type = request.GET.get("type")
        permission = request.data.get("permission")
        users = request.data.get("users")
        prevsusers = request.data.get("prevsusers")
         
        if  type=="folder" :
            folder = Folder.objects.get(id= request.data.get("id"))
            perm = request.user.has_perm('change_folder', folder)
            if perm:
                if "prevsusers" in request.data:
                    prev_user_permissions = get_users_with_perms(folder, attach_perms=True).keys()
                    current_user_permissions =  [ sub['prevuser'] for sub in prevsusers ] 
                    current_user_permissions = User.objects.filter(email__in=current_user_permissions)
                    remove_users = set(prev_user_permissions) - set(current_user_permissions)

                    for update_user in prevsusers:
                        user = User.objects.get(email=update_user["prevuser"])
                        if update_user["userpermission"] == "view":
                            remove_perm('change_folder', user, folder)
                            sub_files = File.objects.filter(folder=folder)
                            if len(sub_files)>0:
                                for subfile in sub_files:
                                    remove_perm('change_file', user, subfile)
                            sub_folders = Folder.objects.filter(parent_directory=folder) 
                            if len(sub_folders)>0:
                                for subfold in sub_folders:
                                    remove_perm('change_folder', user, subfold)

                            sub_files = File.objects.filter(folder__in=sub_folders)
                            if len(sub_files)>0:
                                remove_perm('change_file', user, sub_files)

                            while sub_folders or sub_files:
                                sub_folders = Folder.objects.filter(parent_directory__in=sub_folders)
                                if len(sub_folders)>0:
                                    for subfold in sub_folders:

infobank/templates/infobank/manage_users.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Ulkasemi Info Bank</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#000000" />
  <meta name="description" content="Ecommerce Website Created for Learning" />
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
    rel="stylesheet" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <!-- Bootstrap -->
  <!-- CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" />
  <!-- jQuery and JS bundle w/ Popper.js -->
  <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>

  <link rel="stylesheet" href="{% static " infobank/new_styles.css" %}" />
</head>

<body>
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <!-- NAVBAR & BANNER-->
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand" href="{% url 'infobank:home' %}">
        <h1><span>U</span>LKASEMI</h1>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'infobank:home' %}">Home</a>
          </li>

          <li>
            {% if user.is_authenticated %}
            <div class="dropdown">
              <a class="nav-link" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">{{user.get_full_name}} <i class="fa fa-angle-down"></i></a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="#"><i class="fa fa-cloud-upload"></i>Manage Files</a>
                {% if user.is_superuser %}
                <a class="dropdown-item" href="{% url 'infobank:manage_users' %}"><i class="fa fa-users"></i>Manage
                  Users</a>
                {% endif %}

              </div>
            </div>
            {% else %}
            <a id="myBtn">Login</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
  </div>
  <!-- USER LIST -->
  <section id="page-title" class="section">
    <div class="container">
      <div class="row">
        <div class="col">
          <h5 class="float-left">All Users</h5>
        </div>
        <div class="col">
          <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#signUpModal">
            <i class="fa fa-plus"></i> Add New User
          </button>
        </div>
      </div>
    </div>
  </section>

  <section id="user-list" class="section">
    <div class="container">
      <div class="table-responsive">
        <table class="table table-borderless">
          <thead>
            <tr>
              <th scope="col">Employee</th>
              <th scope="col">Email</th>
              <th scope="col">Permissions</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            {% for each_user in users %}
            <tr>
              <td class="align-middle">{{each_user.get_full_name}}</td>
              <td class="align-middle">{{each_user.email}}</td>
              <td class="align-middle">
                {% if each_user.is_superuser %}
                <h2 class="badge badge-primary">Admin</h2>
                {% elif each_user.has_permissions %}
                <!-- Normal User -->
                {% if each_user.category_set.all.count > 0 %}
                <!-- If User Is Owner of Category -->
                {% for category in each_user.category_set.all %}
                <a href="{% url 'infobank:category_details' category.slug %}">{{category}}</a><br />
                {%endfor %}
                <!-- End of For Loop -->
                {% endif %}
                <!-- Folder Permissions -->
                {% if each_user.folder_set.all.count > 0 %}
                <!-- If User Is Owner of Category -->
                {% for folder in each_user.folder_set.all %}
                <a href="{% url 'infobank:folder_details' folder.id %}">{{folder}}</a><br />
                {% endfor %}
                <!-- End of For Loop -->
                {% endif %}
                <!-- For No Permissions -->
                {% else %}
                <p class="badge badge-danger">No Permissions</p>
                {% endif %}
              </td>
              <td class="align-middle">
                {% if each_user == user or not each_user.is_superuser %}
                <button class="btn btn-primary" disabled>
                  <i class="fa fa-pencil" aria-hidden="true"></i>
                </button>
                {% endif %} {% if not each_user.is_superuser %}
                <button class="btn btn-danger" onclick="showDeleteModal('{{each_user.id}}', '{{each_user.email}}')">
                  <i class="fa fa-trash" aria-hidden="true"></i>
                </button>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

  <!-- Modal -->
  <div class="modal fade" id="signUpModal" data-backdrop="static" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Create New User</h5>
        </div>
        <div class="modal-body">
          <form method="POST" id="signUpForm">
            {% csrf_token %}
            <div class="form-group">
              <label for="email">Email address</label>
              <input type="email" class="form-control" name="email" id="email" placeholder="name@ulkasemi.com"
                required="true" />
            </div>
            <div class="form-group">
              <label for="exampleFormControlInput1">Employee Name</label>
              <div class="row">
                <div class="col">
                  <input type="text" class="form-control" id="first_name" name="first_name" placeholder="First name"
                    required="true" />
                </div>
                <div class="col">
                  <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last name"
                    required="true" />
                </div>
              </div>
            </div>
            <div class="form-group">
              <label for="exampleFormControlInput1">Employee ID</label>
              <input type="text" class="form-control" id="employee_id" name="employee_id"
                placeholder="Employee Office ID" required="true" />
            </div>
            <div class="form-group">
              <label for="exampleFormControlSelect2">Choose Permission Type</label>
              <select class="form-control" name="perm_type" id="perm_type" required="true">
                <option value="" disabled selected>
                  Select Permission Type
                </option>
                <option value="category">Category Owner</option>
                <option value="folder">Folder Owner</option>
              </select>
            </div>
            <div class="form-group" style="display: none" id="category-perm-container">
              <label for="exampleFormControlSelect2">Choose Categories</label>
              <select multiple class="form-control" name="category_set" id="category_set">
                {% for category in categories %}
                <option value="{{category.id}}">{{category}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="form-group" style="display: none" id="folder-perm-container">
              <label for="exampleFormControlSelect2">Choose Folders</label>
              <select multiple class="form-control" name="folder_set" id="folder_set">
                <!-- Loop through categories -->
                {% for category in categories %}
                <!-- if has folders -->
                {% if category.folder_set.all.count > 0 %}
                <option disabled>{{category}}</option>
                {% for folder in category.folder_set.all %}
                <option value="{{folder.id}}">{{folder}}</option>
                {% endfor %} {% endif %} {% endfor %}
              </select>
            </div>
            <!-- <div class="form-group">
                <label for="exampleFormControlTextarea1"
                  >Example textarea</label
                >
                <textarea
                  class="form-control"
                  id="exampleFormControlTextarea1"
                  rows="3"
                ></textarea>
              </div> -->
          </form>
          <p class="eroor-message">Invalid Email or Password.</p>
        </div>
        <div class="modal-footer">
          <button type="reset" form="signUpForm" class="btn ui-btn-close-primary" data-dismiss="modal">
            Close
          </button>
          <button type="submit" form="signUpForm" class="btn btn-primary">
            Create User
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="deleteUserModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete User?</h5>
        </div>
        <div class="modal-body">
          <p>
            Do you really want to delete this user:
            <span id="del-user-email"></span>?
          </p>
        </div>
        <div class="modal-footer">
          <button class="btn ui-btn-close" data-dismiss="modal">
            Cancel
          </button>
          <button type="button" class="btn btn-danger" onclick="deleteUser()">
            Delete
          </button>
        </div>
      </div>
    </div>
  </div>
  <script>
    var del_user_id;

    function showDeleteModal(id, email) {
      del_user_id = id;
      $("#del-user-email").text(email);
      $("#deleteUserModal").modal("show");
    }
    $("#deleteUserModal").on("hidden.bs.modal", function (e) {
      del_user_id = null;
    });

    function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== "") {
        const cookies = document.cookie.split(";");
        for (let i = 0; i < cookies.length; i++) {
          const cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === name + "=") {
            cookieValue = decodeURIComponent(
              cookie.substring(name.length + 1)
            );
            break;
          }
        }
      }
      return cookieValue;
    }
    function deleteUser() {
      $.ajax({
        type: "DELETE",
        url: "/user/" + del_user_id,
        beforeSend: function (xhr) {
          xhr.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));
        },
        success: function (data) {
          if (data.status == "ok") {
            location.reload();
          }
        },
        error: function (data) {
          console.log("Error", data);
        },
      });
    }
  </script>

  <!-- Submit Form -->
  <script>
    $("#perm_type").change(function () {
      if (this.value == "category") {
        $("#folder_set").prop("required", false);
        $("#folder_set").prop("selectedIndex", -1);
        $("#folder-perm-container").css("display", "none");
        $("#category_set").prop("required", true);
        $("#category-perm-container").css("display", "block");
      } else if (this.value == "folder") {
        $("#folder_set").prop("required", true);
        $("#folder-perm-container").css("display", "block");
        $("#category_set").prop("required", false);
        $("#category_set").prop("selectedIndex", -1);
        $("#category-perm-container").css("display", "none");
      }
    });

    // RESET Form on Modal Close
    $("#signUpModal").on("hidden.bs.modal", function (e) {
      $("#signUpForm")[0].reset();
    });
  </script>
  <script>
    $("#signUpForm").on("submit", function (e) {
      e.preventDefault();
      $(".eroor-message").css("display", "none");
      var data = $("#signUpForm").serialize();
      $.ajax({
        type: "POST",
        url: "{% url 'infobank:manage_users' %}",
        data: data,
        success: function (data) {
          if (data.status == "ok") {
            $(".eroor-message").css("display", "none");
            location.reload();
          } else if (data.status == "failed") {
            $(".eroor-message").css("display", "block");
            $(".eroor-message").text(data.message);
          }
        },
        error: function (data) {
          console.log("Error", data);
        },
      });
    });
  </script>
</body>

</html>